# Generated by Django 4.1.7 on 2023-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0002_remove_userprofile_external_id2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='left_token',
            field=models.IntegerField(default=100000),
        ),
    ]
