# Generated by Django 4.1.7 on 2023-05-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0003_alter_promptmodel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptmodel',
            name='history',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
