# Generated by Django 4.1.7 on 2023-05-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0005_dialogue_completion_tokens_dialogue_prompt_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='request_time',
            field=models.IntegerField(default=0),
        ),
    ]
