# Generated by Django 4.1.7 on 2023-05-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0006_dialogue_request_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('image_path', models.EmailField(default='', max_length=200)),
                ('question', models.CharField(default='', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('question', models.EmailField(default='', max_length=1500)),
                ('answer', models.CharField(default='', max_length=2500)),
            ],
        ),
        migrations.AlterField(
            model_name='tokenconsumption',
            name='model_type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'EMBEDDING'), (2, 'CHAT'), (3, 'IMAGE'), (4, 'TRANSLATE'), (5, 'GRAMMAR'), (6, 'SUMMARY'), (7, 'QUIZ')], default=0),
        ),
    ]
