# Generated by Django 4.1.7 on 2023-03-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0007_embeddingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
