# Generated by Django 4.1.7 on 2023-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0007_ocrrecord_quizrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrecord',
            name='response_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizrecord',
            name='response_time',
            field=models.IntegerField(default=0),
        ),
    ]
