# Generated by Django 4.1.7 on 2023-05-25 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0008_ocrrecord_response_time_quizrecord_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrrecord',
            name='username',
        ),
        migrations.RemoveField(
            model_name='quizrecord',
            name='username',
        ),
        migrations.AddField(
            model_name='ocrrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
