# Generated by Django 4.1.7 on 2023-05-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0009_remove_ocrrecord_username_remove_quizrecord_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='request_time',
            field=models.IntegerField(default=0),
        ),
    ]
