# Generated by Django 4.1.7 on 2023-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0010_dialogue_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
