# Generated by Django 4.1.7 on 2023-05-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0011_ocrrecord_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='llm_model',
            field=models.CharField(default='', max_length=25),
        ),
    ]
