# Generated by Django 4.1.7 on 2023-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0013_therapyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingmodel',
            name='reject_message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
