# Generated by Django 4.1.7 on 2023-06-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0015_visitorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorprofile',
            old_name='therapy_id',
            new_name='uuid',
        ),
    ]
