# Generated by Django 4.1.7 on 2023-06-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0016_rename_therapy_id_visitorprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorprofile',
            name='diagnosis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitorprofile',
            name='evidence',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='visitorprofile',
            name='marriage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
