# Generated by Django 4.1.7 on 2023-06-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0017_alter_visitorprofile_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingmodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
