# Generated by Django 4.1.7 on 2023-06-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0018_embeddingmodel_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=500)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embedding.embeddingmodel')),
            ],
        ),
    ]
