# Generated by Django 4.1.7 on 2023-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0019_embeddingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingdocument',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
