# Generated by Django 4.1.7 on 2023-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0020_embeddingdocument_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingdocument',
            name='summarization',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
