# Generated by Django 4.1.7 on 2023-06-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0023_suicideassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('uuid', models.CharField(default='', max_length=20)),
                ('message', models.CharField(default='', max_length=1500)),
                ('role', models.CharField(default='', max_length=10)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embedding.visitorprofile')),
            ],
        ),
    ]
