# Generated by Django 4.1.7 on 2023-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0024_visitordialogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordialogue',
            old_name='uuid',
            new_name='dialogue_uuid',
        ),
        migrations.AddField(
            model_name='visitordialogue',
            name='msg_uuid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
