# Generated by Django 4.1.7 on 2023-06-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0025_rename_uuid_visitordialogue_dialogue_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordialogue',
            name='ack',
            field=models.BooleanField(default=False),
        ),
    ]
