# Generated by Django 4.1.7 on 2023-06-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0026_visitordialogue_ack'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepressionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('assessment', models.CharField(default='', max_length=20)),
                ('evidence', models.CharField(blank=True, default='', max_length=1500)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embedding.visitorprofile')),
            ],
        ),
    ]
