# Generated by Django 4.1.7 on 2023-06-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0028_rename_assessment_depressionassessment_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorprofile',
            name='pin',
            field=models.CharField(default='', max_length=5),
        ),
    ]
