# Generated by Django 4.1.7 on 2023-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0029_visitorprofile_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorprofile',
            name='pin',
            field=models.CharField(default='', max_length=6),
        ),
    ]
