# Generated by Django 4.1.7 on 2023-06-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0030_alter_visitorprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorprofile',
            name='age_range',
            field=models.CharField(default='', max_length=20),
        ),
    ]
