# Generated by Django 4.1.7 on 2023-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0032_alter_suicideassessment_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrecord',
            name='token_amount_request',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizrecord',
            name='token_amount_response',
            field=models.IntegerField(default=0),
        ),
    ]
