# Generated by Django 4.1.7 on 2023-06-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0035_therapyassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=300)),
                ('area', models.CharField(default='', max_length=30)),
                ('mobile', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=1000)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('size', models.CharField(default='', max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('pi_id', models.CharField(default='', max_length=100)),
                ('order_state', models.CharField(default='', max_length=100)),
                ('created_time', models.IntegerField(default=0)),
                ('paid_time', models.IntegerField(default=0)),
                ('delivery_time', models.IntegerField(default=0)),
                ('delivery_id', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
