# Generated by Django 4.1.7 on 2023-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0036_fruitorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitorder',
            name='order_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fruitorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
