MODEL_TYPES_UNKNOWN = 0
MODEL_TYPES_EMBEDDING = 1
MODEL_TYPES_CHAT = 2
MODEL_TYPES_IMAGE = 3
MODEL_TYPES_TRANSLATE = 4
MODEL_TYPES_GRAMMAR = 5
MODEL_TYPES_SUMMARY = 6
MODEL_TYPES = (
    (MODEL_TYPES_UNKNOWN, 'UNKNOWN'),
    (MODEL_TYPES_EMBEDDING, 'EMBEDDING'),
    (MODEL_TYPES_CHAT, 'CHAT'),
    (MODEL_TYPES_IMAGE, 'IMAGE'),
    (MODEL_TYPES_TRANSLATE, 'TRANSLATE'),
    (MODEL_TYPES_GRAMMAR, 'GRAMMAR'),
    (MODEL_TYPES_SUMMARY, 'SUMMARY'),
)

CHAT_TYPES_NO = 'Common AI'
CHAT_TYPES_ASSISTANT = 'Assistant'
CHAT_TYPES_PRESIDENT = 'Mr. President'
CHAT_TYPES_THERAPIST = 'Therapist'
CHAT_TYPES = (
    (CHAT_TYPES_NO, 'Common AI'),
    (CHAT_TYPES_ASSISTANT, 'Virtual Assistant'),
    (CHAT_TYPES_PRESIDENT, 'Mr. President'),
    (CHAT_TYPES_THERAPIST, 'Therapist'),
)

TRAINING_MODELS_A = 'text-ada-001'
TRAINING_MODELS_B = 'text-babbage-001'
TRAINING_MODELS_C = 'text-curie-001'
TRAINING_MODELS_D = 'text-davinci-003'
TRAINING_MODELS_A1 = 'ada:ft-personal-2023-03-01-22-16-31'
TRAINING_MODELS = (
    (TRAINING_MODELS_A, 'OpenAI text model A'),
    (TRAINING_MODELS_B, 'OpenAI text model B'),
    (TRAINING_MODELS_C, 'OpenAI text model C'),
    (TRAINING_MODELS_D, 'OpenAI text model D'),
    (TRAINING_MODELS_A1, 'OpenAI fine tuning text model A1'),
)