MODEL_TYPES_UNKNOWN = 0
MODEL_TYPES_EMBEDDING = 1
MODEL_TYPES_CHAT = 2
MODEL_TYPES_IMAGE = 3
MODEL_TYPES_TRANSLATE = 4
MODEL_TYPES_GRAMMAR = 5
MODEL_TYPES_SUMMARY = 6
MODEL_TYPES = (
    (MODEL_TYPES_UNKNOWN, 'UNKNOWN'),
    (MODEL_TYPES_EMBEDDING, 'EMBEDDING'),
    (MODEL_TYPES_CHAT, 'CHAT'),
    (MODEL_TYPES_IMAGE, 'IMAGE'),
    (MODEL_TYPES_TRANSLATE, 'TRANSLATE'),
    (MODEL_TYPES_GRAMMAR, 'GRAMMAR'),
    (MODEL_TYPES_SUMMARY, 'SUMMARY'),
)

CHAT_TYPES_NO = 'Common AI'
CHAT_TYPES_ASSISTANT = 'Assistant'
CHAT_TYPES_PRESIDENT = 'Mr. President'
CHAT_TYPES = (
    (CHAT_TYPES_NO, 'Common AI'),
    (CHAT_TYPES_ASSISTANT, 'Virtual Assistant'),
    (CHAT_TYPES_PRESIDENT, 'Mr. President'),
)