# Generated by Django 4.1.7 on 2023-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='external_id2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_token',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='used_token',
            field=models.IntegerField(default=0),
        ),
    ]
