# Generated by Django 4.1.7 on 2023-03-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0008_contact_embeddingmodel_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=20)),
                ('message', models.EmailField(default='', max_length=5000)),
                ('dialogue_id', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
